```{r set up, message=FALSE, warning= FALSE}

getwd()

library(here)
library(lubridate)
library(dplyr)
library(zoo)

RDUPrecip<-read.csv(here("Hydrology", "Assignment 3", "Raw", "RDU_precip_daily_cm_1942_to_2020-8-10(in).csv" ))

RDUPrecip$DATE<-mdy(RDUPrecip$DATE)
```



```{r creating 48 hour hazen intervals}

##ranking events and finding the Hazen Interval
RDUPrecipProcessed<-RDUPrecip%>% 
  rename(Precipitation = PRCP) %>%
  select (DATE:Precipitation) %>%
   mutate(
     Precipitation=(Precipitation*0.0393701), #convert to inches from mm
     n=dense_rank(desc(Precipitation))) %>% #ranking
  arrange(n) %>% 
  mutate(
    Percent_Chance_of_Rain = (100*(2*n-1)/(2*27844)), #creating Hazen Number
  Return_Period = (100/Percent_Chance_of_Rain), #finding interval
  Return_Period_Annual = (Return_Period/365) #annualizing
  )
 
 



```


```{r}
summary(RDUPrecipProcessed)

RDUPlot<-RDUPrecipProcessed %>% 
  ggplot(aes(x=-n, y=Precipitation)
         )+
  geom_line()+
  
plot(RDUPlot)

RDUPlot2<-RDUPrecipProcessed %>% 
  ggplot(aes(x=-n, y=Precipitation)
         )+
  geom_line()



plot(RDUPlot2)


```

```{r max per year}


RDUPrecipProcessedYearMax<-RDUPrecip%>% 
  rename(Precipitation = PRCP) %>%
  select (DATE:Precipitation) %>%
  group_by
   mutate(
     Precipitation=(Precipitation*0.0393701), #convert to inches from mm
     n=dense_rank(desc(Precipitation))) %>% #ranking
  arrange(n) %>% 
  mutate(
    Percent_Chance_of_Rain = (100*(2*n-1)/(2*27844)), #creating Hazen Number
  Return_Period = (100/Percent_Chance_of_Rain), #finding interval
  Return_Period_Annual = (Return_Period/365) #annualizing
  )
 


```



